### ISSUE TITLE
Unable to use storage

### ISSUE THREAD

**Issue by mvhirsch** [thumbor/thumbor-aws#1]
I'm using [minio](https://github.com/minio/minio) (an AWS S3 compatible storage) for testing this extension. I've bootstrapped it via docker-compose, and it usually works fine. But requesting an image, it fails with following error:

```
thumbor_1  | 2022-01-22 16:31:10 thumbor:ERROR ERROR: Traceback (most recent call last):
thumbor_1  |   File "/usr/local/thumbor/.local/lib/python3.10/site-packages/tornado/web.py", line 1704, in _execute
thumbor_1  |     result = await result
thumbor_1  |   File "/usr/local/thumbor/.local/lib/python3.10/site-packages/thumbor/handlers/imaging.py", line 97, in get
thumbor_1  |     return await self.check_image(kw)
thumbor_1  |   File "/usr/local/thumbor/.local/lib/python3.10/site-packages/thumbor/handlers/imaging.py", line 26, in check_image
thumbor_1  |     exists = await self.context.modules.storage.exists(
thumbor_1  |   File "/usr/local/thumbor/.local/lib/python3.10/site-packages/thumbor_aws/storage.py", line 73, in exists
thumbor_1  |     return await self.object_exists(path)
thumbor_1  |   File "/usr/local/thumbor/.local/lib/python3.10/site-packages/thumbor_aws/s3_client.py", line 234, in object_exists
thumbor_1  |     await client.get_object_acl(
thumbor_1  |   File "/usr/local/thumbor/.local/lib/python3.10/site-packages/aiobotocore/client.py", line 187, in _make_api_call
thumbor_1  |     raise error_class(parsed_response, operation_name)
thumbor_1  | botocore.exceptions.ClientError: An error occurred (XMinioInvalidObjectName) when calling the GetObjectAcl operation: Object name contains unsupported characters.
thumbor_1  | 
thumbor_1  | 2022-01-22 16:31:10 tornado.access:ERROR 500 GET /unsafe/https://raw.githubusercontent.com/thumbor/thumbor/master/docs/images/blur_before.jpg (172.18.83.1) 68.94ms
```

Calling with: `http://localhost:8888/unsafe/https://raw.githubusercontent.com/thumbor/thumbor/master/docs/images/blur_before.jpg`

Using the following configuration:

```
      STORAGE: thumbor_aws.storage
      AWS_STORAGE_S3_ENDPOINT_URL: http://minio:9000
      AWS_STORAGE_BUCKET_NAME: mystorage
      AWS_STORAGE_S3_ACCESS_KEY_ID: generated
      AWS_STORAGE_S3_SECRET_ACCESS_KEY: generated
```

The AWS bucket is accessible: 

![Screenshot from 2022-01-22 17-42-19](https://user-images.githubusercontent.com/573047/150647683-c0babc66-b74a-4ec8-b204-038668e3674b.png)

According [to this issue](https://github.com/minio/minio/issues/3390), there was an issue in the client library. Maybe there is some escaping missing?

**Comment by heynemann** [comment]
Can you help me setup minio using docker so we can also test it here?

**Comment by mvhirsch** [comment]
Sure thing!

To run minio with docker, just run this command:

```bash
# create bucket
mkdir -p minio/thumbor

# run docker, mounting bucket as volume
docker run --rm -v $(pwd)/minio/:/data -p9000:9000 -p9001:9001 minio/minio:RELEASE.2022-01-08T03-11-54Z server /data --console-address :9001
```

First we need to create the bucket (`mkdir`). Minio is capable of automatically handle it as bucket after mounting it. The command above binds the console you may log into at `http://localhost:9001` (default credentials will get logged console, usually `minioadmin:minioadmin`).

You can access the S3 storage (please note the port `9000`) with the following thumbor-aws configuration:

```
RESULT_STORAGE = 'thumbor_aws.result_storage'
AWS_RESULT_STORAGE_S3_ENDPOINT_URL = 'http://localhost:9000'
AWS_RESULT_STORAGE_BUCKET_NAME = 'thumbor'
AWS_RESULT_STORAGE_ROOT_PATH = '/thumbs'
AWS_RESULT_STORAGE_S3_ACCESS_KEY_ID = 'minioadmin'
AWS_RESULT_STORAGE_S3_SECRET_ACCESS_KEY = 'minioadmin'
RESULT_STORAGE_STORES_UNSAFE = True

STORAGE = 'thumbor_aws.storage'
AWS_STORAGE_S3_ENDPOINT_URL = 'http://localhost:9000'
AWS_STORAGE_BUCKET_NAME = 'thumbor'
AWS_STORAGE_S3_ACCESS_KEY_ID = 'minioadmin'
AWS_STORAGE_S3_SECRET_ACCESS_KEY = 'minioadmin'
```

**Comment by heynemann** [comment]
Can you try it out with release 0.3.0 of thumbor-aws?

**Comment by heynemann** [comment]
Since AWS returns a location header, I assumed every provider would. Now I allow you to configure the fallback location for when the location header is not found. Can you try 0.3.1?

**Comment by heynemann** [comment]
Sorry for the issues. Not so easy to make it compatible with every cloud solution :D

**Comment by mvhirsch** [comment]
I'm not really sure what exactly changed, since I forgot to set the new `AWS_DEFAULT_LOCATION` on first try with 0.3.1, and it worked. Still getting warnings, but I think this is intended.

I guess this is a good start, since it works now out-of-the-box. Maybe I have to correctly configure minio/thumbor-aws to play well. I'll take a look at it the next days. For now, I consider this as done. Thank you!

Next time I'll add a running docker-compose.yaml, which I guess will help you much more? :grinning:
