### ISSUE TITLE
lower performance compared to tc_aws

### ISSUE THREAD

**Issue by mello7tre** [thumbor/thumbor-aws#114]
Hi, i switched from [tc_aws](https://github.com/thumbor-community/aws/tree/master) [7.0.2] to [thumbor-aws](https://github.com/thumbor/thumbor-aws) [0.6.0], but i had to revert cause response time increased by ~ 200 ms.
My configuration is very simple and i use loader only (Bucket is get from url).

thumbor-aws conf:
```
AWS_LOADER_REGION_NAME = "eu-west-1"                                      
AWS_LOADER_BUCKET_NAME = None                                                          
AWS_LOADER_ROOT_PATH = ""                                                              
AWS_STORAGE_REGION_NAME = ""                                                           
AWS_STORAGE_S3_SECRET_ACCESS_KEY = ""                                                  
AWS_STORAGE_S3_ACCESS_KEY_ID = ""                                                      
AWS_STORAGE_S3_ENDPOINT_URL = ""
```
tc_aws conf:
```
TC_AWS_REGION = "eu-west-1"
TC_AWS_ENABLE_HTTP_LOADER = True
```

Could be probably related to the improvements made on `tc_aws` by @amanagr https://github.com/amanagr/aws/pull/1 ?
(For whole PR thread: https://github.com/thumbor-community/aws/pull/147).
I will try to investigate further and let you know if i discover something relevant.

Regards, Alberto.

**Comment by mello7tre** [comment]
I made further tests and tried to use same approach of `tc_aws` to re-use s3_client.
I changed s3_client `S3Client` class to:
```
class S3Client:
    _client = None
    _instances = {}

    @staticmethod
    def __new__(cls, context):
        key = (context.config.AWS_LOADER_BUCKET_NAME, context.config.AWS_LOADER_REGION_NAME, context.config.AWS_LOADER_S3_ENDPOINT_URL)

        if not cls._instances.get(key):
            cls._instances[key] = super(S3Client, cls).__new__(cls)

        return cls._instances[key]

```
and checked if  `self._client` does exist before creating a new one.

As a result performance are now comparable to the `tc_aws` one!

Mine was only a test, but i can confirm you that the difference in response time is caused by the "multiple" s3 client initialization compared to initialize it just one time (for bucket, region, endpoint).

**Comment by mello7tre** [comment]
That fix work only if you do not  put code in an async with context and so do not use aiobotocore > 0.12.

Just for info the PR https://github.com/thumbor/thumbor-aws/pull/19, at the end re-use only the session not the client, and the bigger effort is on creating the whole s3 client.

Currently we have a fast `tc_aws` but that to re-use aiobotocore s3 client need to use an old (very) version.
And an up to date `thumbor-aws` that is not usable in production, compared to tc_aws, because increase reponse time of 0.2 sec (and under an high number of request, also memory usage).

**Comment by pfcodes** [comment]
Thanks for this heads up

**Comment by mello7tre** [comment]
just for info i have mixed `tc_aws` solutions https://github.com/thumbor/thumbor-aws/pull/19 and https://github.com/thumbor-community/aws/pull/142/commits/b5058e6b9fec7354629acc6d5df423e0310bb0cd in `thumbor-aws`
(for the second one i had to put `_client = None` in class definition root and not in class `__init__`)

This way i have `thumbor-aws` that use a persistent s3 client and that work using an up to date aiobotocore [2.x].
(i have it running in production without any problem so far)
