### ISSUE TITLE
Cannot re-use old result storage from tc_aws

### ISSUE THREAD

**Issue by oliverschewe** [thumbor/thumbor-aws#16]
Is it possible to remove the additional `/default` path from result storage?
https://github.com/thumbor/thumbor-aws/blob/main/thumbor_aws/result_storage.py#L164

Otherwise it is not possible to re-use an existing s3 result storage from tc_aws, because it does not contain this.

tc-aws path looks like BUCKET_NAME + ROOT_PATH + IMAGE_URL_PATHS
thumbor-aws path looks like BUCKET_NAME + ROOT_PATH + **/default** + IMAGE_URL_PATHS

**Comment by guilhermef** [comment]
@heynemann can we remove the prefix when it's not a webp image?

**Comment by heynemann** [comment]
I think so :) Do you want to go for it @guilhermef ?

**Comment by guilhermef** [comment]
Released on: https://github.com/thumbor/thumbor-aws/releases/tag/0.4.2
