### ISSUE TITLE
Breaking change in result storage v0.6.0

### ISSUE THREAD

**Issue by sergeief** [thumbor/thumbor-aws#171]
It appears there was a breaking change in results storage path format. This made previous results unavailable in the new version.

In the new version, `auto_webp` is prepended to the root path.

Before: `<root-path>/auto_webp/...`
Now: `auto_webp/<root-path>/...`

https://github.com/thumbor/thumbor-aws/commit/8e14f1324908c8f3ade3f045366361d8178aeb91#diff-6dc50ab2e1f1f5844e51b0d4d2994f9e056ede0cf3244216353b24b6103d9a3eR164

**Comment by nicholascapo** [comment]
Not stale

**Comment by duffn** [comment]
Not stale.

**Comment by guilhermef** [comment]
@sergeief PR #200 should fix it.
