### ISSUE TITLE
Missing STORAGE_ROOT_PATH

### ISSUE THREAD

**Issue by mvhirsch** [thumbor/thumbor-aws#2]
Just playing around and just noticed I'm missing a configuration: `STORAGE_ROOT_PATH` (or similar). Didn't find evidence in code base :sweat_smile: 

A `AWS_RESULT_STORAGE_ROOT_PATH` [does exist, indeed](https://github.com/thumbor/thumbor-aws/blob/286c6b42f2e28023da6097f38522575b73f0d968/thumbor_aws/result_storage.py#L51).

**Comment by heynemann** [comment]
Fixed in 0.3.0. Also added to docs.
