### ISSUE TITLE
Fallback HTTP Loader support

### ISSUE THREAD

**Issue by karptonite** [thumbor/thumbor-aws#268]
This was previously discussed here: #44 and here: #45. TC_AWS had an option `TC_AWS_ENABLE_HTTP_LOADER` that allowed images to be loaded both via S3 and HTTP. Any chance of support for that again? We don't really want to have to run two Thumbor instances, one for S3, and one for HTTP.

**Comment by karptonite** [comment]
@heynemann we have switched back to tc_aws for now to get around this issue, but we’d prefer to move to this package, since it seems better supported. Is this an unusual use case?

**Comment by asokani** [comment]
We’re also still using the outdated tc_aws because of this. I believe the fallback functionality isn't difficult so why don't have it?

**Comment by mihkel** [comment]
> We’re also still using the outdated tc_aws because of this. I believe the fallback functionality isn't difficult so why don't have it?

The functionality is dead simple and I've created my own loader containing both but in my mind there's like a bit of a conflict here and what I mean is that the aws loader should do what the name says ... load the images from aws and for the http loader a http based loader should be used. And I really miss that Thumbor has chosen a loader logic like it currently has ... would be really great if it provided an option to chain loaders to make some kind of a fallback system of your liking.

**Comment by karptonite** [comment]
@heynemann making another pitch for this. This is still an issue preventing us from migrating to this package.
