### ISSUE TITLE
Optional ROOT_PATH parameter

### ISSUE THREAD

**Issue by beeyev** [thumbor/thumbor-aws#30]
First of all, thank you for the great plugin.

Could you please make it possible to store source and resulting files at the root of storage (bucket)? 
Without the need to define *_STORAGE_ROOT_PATH 
```
http://minio:9000/img-cache/rs/default/unsafe/300x400/yezhik.jpg
The `/rs` needs to be removed
```
And I have another question, what `/default/` stands for in the path of the resulting file?

**Comment by guilhermef** [comment]
@beeyev we've addressed the `/default/` part in this issue: https://github.com/thumbor/thumbor-aws/issues/16

**Comment by guilhermef** [comment]
@beeyev is there an error when you set *_STORAGE_ROOT_PATH to an empty string?

**Comment by beeyev** [comment]
For example, if I set `AWS_RESULT_STORAGE_ROOT_PATH=''`

The path will contain double slashes 
```
http://minio:9000/img-cache//unsafe/300x400/yezhik.jpg
```

**Comment by guilhermef** [comment]
I cannot replicate this behavior on the tests, do you think you can create a PR to address it?

**Comment by beeyev** [comment]
You can find this path with doubled slashes in logs if you enable `debug` mode.
