### ISSUE TITLE
Remove Double Slashes From URL 

### ISSUE THREAD

**Issue by beeyev** [thumbor/thumbor-aws#31]
There are some cases, when the resulting path contains double slashes. 
For example
```
http://minio:9000//img-cache//rs/default/unsafe/430x100/thumbor.jpg
```

Could you please make an additional check when building the path ?

**Comment by guilhermef** [comment]
@beeyev, can you create a PR to help us reproduce this scenario?

**Comment by beeyev** [comment]
If you set these variables like this:
```
AWS_RESULT_STORAGE_BUCKET_NAME='img-cache'
AWS_RESULT_STORAGE_S3_ENDPOINT_URL='http://minio:9000/'
AWS_RESULT_STORAGE_ROOT_PATH='/abc'
```

The result path will contain double slashes:
```
http://minio:9000/img-cache//abc/unsafe/320x400/yezhik.jpg
```

**Comment by guilhermef** [comment]
I'm sorry @beeyev, but I couldn't reproduce this issue
