### ISSUE TITLE
Ability to use instance credentials

### ISSUE THREAD

**Issue by jmortlock** [thumbor/thumbor-aws#40]
Hi

Is there any way to use instance profile credentials with this library?
Looking through the codebase it seems like access key / secret is the only option?

Thanks

**Comment by guilhermef** [comment]
Hi John,
It will work, you don’t need to set access key and secret.

**Comment by jmortlock** [comment]
Ah OK. Thanks for clarifying.

I think the issue is how the docker project i am using sets the default values credentials, and I can't figure out how I can set it back to "None" using the envtmpl stuff

Anyway i have opened a PR https://github.com/mvhirsch/thumbor-docker/pull/12 to switch the default to be None (rather than the current "") which I think will fix my problem.

In the meanwhile I will continue using access key.

Thanks
