### ISSUE TITLE
Difficulties to configure only Loader

### ISSUE THREAD

**Issue by P0ssuidao** [thumbor/thumbor-aws#57]
I'm trying to configure just the loader but I'm getting some errors.

I did the tests using 2 approaches and both without success.

my configuration:
```
AWS_LOADER_REGION_NAME = 'us-east-1'
AWS_LOADER_S3_SECRET_ACCESS_KEY = ''
AWS_LOADER_S3_ACCESS_KEY_ID = ''
AWS_LOADER_S3_ENDPOINT_URL = 'https://s3.us-east-1.amazonaws.com'
AWS_LOADER_ROOT_PATH = ''
AWS_LOADER_BUCKET_NAME = 'mybucket'
```

## LOADER = "thumbor_aws.loader"

Error:
```
ERROR [BaseHandler] get_image failed for url . error: `AWS_STORAGE_REGION_NAME`
```

## LOADER = thumbor.loaders.http_loader
Error:
```
thumbor:WARNING ERROR retrieving image "IMAGE URL" : HTTP 599: [Errno -2] Name or service not known
```

I tried to use the same configuration that I have in 6.7 with compatibility mode but without success.

Can you tell me if I'm doing something wrong?

**Comment by arturbani** [comment]
@P0ssuidao did you have any progress in this? I'm having similar issues

**Comment by P0ssuidao** [comment]
> @P0ssuidao did you have any progress in this? I'm having similar issues

Not yet =/

**Comment by Tenzer** [comment]
To provide a bit more detail, a stacktrace from before I got those settings configured:
```
2022-09-28 09:28:43 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/thumbor/handlers/__init__.py", line 212, in get_image
    result = await self._fetch(self.context.request.image_url)
  File "/usr/local/lib/python3.10/site-packages/thumbor/handlers/__init__.py", line 805, in _fetch
    loader_result = await self.context.modules.loader.load(
  File "/usr/local/lib/python3.10/site-packages/thumbor_aws/loader.py", line 88, in load
    status_code, body, last_modified = await client.get_data(
  File "/usr/local/lib/python3.10/site-packages/thumbor_aws/s3_client.py", line 150, in get_data
    async with self.get_client() as client:
  File "/usr/local/lib/python3.10/site-packages/thumbor_aws/s3_client.py", line 95, in get_client
    region_name=self.region_name,
  File "/usr/local/lib/python3.10/site-packages/thumbor_aws/s3_client.py", line 46, in region_name
    "region_name", self.config.AWS_STORAGE_REGION_NAME
  File "/usr/local/lib/python3.10/site-packages/derpconf/config.py", line 223, in __getattr__
    raise AttributeError(name)
AttributeError: AWS_STORAGE_REGION_NAME
```

I'm guessing `thumbor_aws.s3_client` expects the settings from `thumbor_aws.storage` to be set, even if that module isn't used.

A possible way to fix this, would be to move all the configuration options higher up in the library, to make sure they always are defined, regardless of which parts of thumbor-aws we are using.

**Comment by Tenzer** [comment]
Please don't close this issue as being stale. It's not an issue that solves itself by not doing anything.

**Comment by P0ssuidao** [comment]
Please don't close this issue as being stale.

**Comment by guilhermef** [comment]
I'll move the client config to each of the Thumbor modules, it should prevent this error from happening.
