### ISSUE TITLE
Location Headers was not found in response

### ISSUE THREAD

**Issue by Tenzer** [thumbor/thumbor-aws#65]
Having just migrated from Thumbor 6 and tc-aws to Thumbor 7 and thumbor-aws, I got hit with a stream of these warning messages:

> Unable to process response from AWS to \<URL\>: Location Headers was not found in response

I worked around it by changing the logging level of Thumbor to error (`--log-level=error`), but looking into this further I'm surprised everybody isn't hit by it, as I can't work out when the location header would be set on a file.

I tried to both upload a file to an S3 bucket with website hosting enabled and without, using `aiobotocore` like thumbor-aws does, and neither contained a `location` key in the `HTTPHeaders` dict. What is expected to set this header?

Would it perhaps be an idea to raise a [warning](https://docs.python.org/3/library/warnings.html) rather than logging a warning message, so a line isn't emitted for each request Thumbor gets?
Is the warning message necessary at all?

**Comment by Tenzer** [comment]
Please don't close this issue as being stale. It's not an issue that solves itself by not doing anything.

**Comment by guilhermef** [comment]
@heynemann @Tenzer is right, I couldn't find the `location` header in the S3 documentation: https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html

Can we just remove this check?
