### ISSUE TITLE
aws loader prepends key path with `/` when root path is an empty string

### ISSUE THREAD

**Issue by thomasf** [thumbor/thumbor-aws#7]
path to object becomes invalid like `/some/path.jpeg`, it looks it might only be an issue when root path is empty which it is required to be in my case.

A very quick fix for testing that might not be the real solution below:

```diff
diff --git a/thumbor_aws/loader.py b/thumbor_aws/loader.py
index d67b1eb..ef6fa87 100644
--- a/thumbor_aws/loader.py
+++ b/thumbor_aws/loader.py
@@ -103,4 +103,4 @@ async def load(context, path):

 def normalize_url(prefix: str, path: str) -> str:
     """Function to normalize URLs before reaching into S3"""
-    return f"{prefix.rstrip('/')}/{path.lstrip('/')}"
+    return f"{prefix.rstrip('/')}/{path.lstrip('/')}".lstrip("/")
```

I guess that in some s3 compatible a leading `/` could possibly be a valid key so maybe a more robust solution is needed.

**Comment by thomasf** [comment]
Tell me any thoughts and if you want a pull request, we can't migrate to thumbor 7.x without this.

**Comment by heynemann** [comment]
Would love a PR here as well :D

**Comment by thomasf** [comment]
bad bot
