### ISSUE TITLE
Is the pycurl dependency really necessary?

### ISSUE THREAD

**Issue by aaugustin** [thumbor/thumbor-aws#84]
pycurl is slightly difficult to install, as it requires compilation and doesn't offer wheel.

It's an optional dependency of thumbor. I see it's a mandatory dependency of thumbor-aws but it doesn't appear to be used anywhere. Am I missing a reason why it's necessary?

**Comment by guilhermef** [comment]
@aaugustin you're right, I'll remove this dependency.
